---
title: "Describe HoNOS items, severity scores, and clusters"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{describe_honos}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Describe HoNOS item labels

- `as_item_desc()`: Add item descriptions (For 13 and 18 item versions of the HoNOS)
 
```{r}

library(honos)

honos_longish <- honos_data %>% 
  pivot_honos_longer(value_vars_current = c("q1", "q2", "q3", "q4", "q5", "q6", "q7", 
                                            "q8", "q9", "q10", "q11", "q12", "q13"),
                     prob_var_item8 = c("q8_prob"),
                     spec_var_item8 = c("q8_spec"),
                     value_vars_history = c("qa", "qb", "qc", "qd", "qe"), 
                     pivot = "item_scores") 

honos_longish

```

```{r}

# make use of all these description functions I wrote
honos_longish %>% 
  dplyr::mutate(item = as_item_desc(item)) %>% 
  dplyr::mutate(prob = as_i8_desc(prob)) %>% 
  dplyr::mutate(value = as_severity_desc(value))

```

## Compare short and long labels

```{r}
honos_longish %>% 
  dplyr::mutate(value = as_severity_desc(value, short_labels = TRUE))
```

```{r}
honos_longish %>% 
  dplyr::mutate(value = as_severity_desc(value, short_labels = FALSE))
```

